apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name:  {{ .Values.init.spcName }} 
spec:
  provider: vault
  parameters:
    vaultAddress: {{ .Values.vault.address }}
    vaultKubernetesMountPath: {{ .Values.vault.kubernetesMountPath }}
    roleName: {{ .Values.vault.vaultRole }}
    objects: |
      - objectName: "tls-crt"
        secretPath: {{ .Values.vault.secretsPath }} 
        secretKey: "tls.crt"
      - objectName: "tls-key"
        secretPath: {{ .Values.vault.secretsPath }} 
        secretKey: "tls.key"
      - objectName: "password"
        secretPath: {{ .Values.vault.secretsPath }} 
        secretKey: "jkspass"

