apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.nameSpace }}-spc
spec:
  provider: vault
  parameters:
    vaultAddress: "http://external-vault:8200"
    vaultKubernetesMountPath: {{ .Values.clusterName }}-{{.Values.nameSpace}}
    roleName: {{ .Values.clusterName }}-{{.Values.nameSpace}}-role
    objects: |
      - objectName: "tls-crt"
        secretPath: "secret/data/{{ .Values.clusterName }}-secrets"
        secretKey: "tls.crt"
      - objectName: "tls-key"
        secretPath: "secret/data/{{ .Values.clusterName }}-secrets"
        secretKey: "tls.key"
      - objectName: "jkspass"
        secretPath: "secret/data/{{ .Values.clusterName }}-secrets"
        secretKey: "jkspass"

